---
- name: "Zero-Day Patch Compliance Check"
  hosts: "{{ target_collection }}"
  tasks:
    - name: Define Target Patching Level
      microsoft.mecm.mecm_package_info:
        name: "{{ patch_name }}"
        site_code: "PS1"
      register: pkg_info

    - name: Verify Device Compliance
      ansible.builtin.debug:
        msg: "CRITICAL: Device requires {{ patch_name }}. Starting drain."
