- name: Phase 5 - Post-Patch Validation & Restore
  hosts: web_servers
  tasks:
    - name: Wait for Web Service Port to be Ready
      # Ensure IIS is actually listening before we proceed
      ansible.windows.win_wait_for:
        port: 80
        state: started
        timeout: 300
      register: port_check

    - name: Perform Application Health Check (HTTP Get)
      # Check a specific local health-check URL to verify the app logic is running
      ansible.windows.win_uri:
        url: "http://localhost/healthcheck.aspx"
        return_content: yes
      register: app_health
      failed_when: "'Healthy' not in app_health.content"

    - name: Final Site-Wide Compliance Refresh
      # Tell MECM to run one last scan so the console shows 'Compliant'
      delegate_to: cm1.corp.contoso.com
      microsoft.mecm.client_action:
        name: "SoftwareUpdateComplianceScan"
        collection: "All Web Servers"

    - name: Re-Enable Traffic (Restore to Load Balancer)
      # Now that health is 100%, bring the server back online
      win_shell: "Set-NetIPAddress -InterfaceAlias 'External' -SkipAsSource $false"