---
- name: Compliance Assertion
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Check Deployment Status from MECM
      microsoft.mecm.software_update_deployment_info:
        site_code: "PS1"
        name: "web-security-patches"
        collection_name: "PROD-Web-Servers"
      register: deploy_status

    - name: Assert all servers are compliant
      ansible.builtin.assert:
        that:
          - deploy_status.software_update_deployments[0].compliant_count == deploy_status.software_update_deployments[0].target_count
        fail_msg: "Compliance Failure: Web servers are missing required patches. Triggering Drain Workflow."
