---
- name: Compliance Assertion
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Check Deployment Status from MECM
      microsoft.mecm.software_update_deployment_info:
        site_code: "PS1"
        name: "Security-Web-Patching" # Updated to match your screenshot
        collection_name: "PROD-Web-Servers"
      register: deploy_status

    - name: "Audit Deployment Configuration"
      ansible.builtin.debug:
        msg: 
          - "Deployment Name: {{ deploy_status.software_update_deployments[0].name }}"
          - "Deployment Type: {{ deploy_status.software_update_deployments[0].deployment_type }}"
          - "Deadline Set: {{ deploy_status.software_update_deployments[0].deadline_time | default('NONE') }}"

    - name: Assert Deployment is Enforced
      ansible.builtin.assert:
        that:
          - deploy_status.software_update_deployments[0].deadline_time != ""
        fail_msg: "Compliance Failure: No enforcement deadline detected. Fleet remediation required."