---
- name: Compliance Assertion
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Check Deployment Status from MECM
      microsoft.mecm.software_update_deployment_info:
        site_code: "PS1"
        name: "web-security-patches"
        collection_name: "PROD-Web-Servers"
      register: deploy_status

    - name: "DEMO: Displaying Current Compliance Metrics"
      ansible.builtin.debug:
        msg: 
          - "Target Count: {{ deploy_status.software_update_deployments[0].compliance_status.target_count }}"
          - "Compliant Count: {{ deploy_status.software_update_deployments[0].compliance_status.compliant_count }}"
      # This looks great in the Arcade logs to show the "gap"

    - name: Assert all servers are compliant
      ansible.builtin.assert:
        that:
          - deploy_status.software_update_deployments[0].compliance_status.compliant_count == deploy_status.software_update_deployments[0].target_count
        fail_msg: "Compliance Failure: Web servers are missing required patches. Triggering Drain Workflow."