- name: Post-Patch Validation & Restore
  hosts: MainMECM  # Changed from web_servers
  gather_facts: false
  tasks:
    - name: "VALIDATION! Waiting for Web Service Port (80) to be Ready"
      ansible.windows.win_wait_for:
        port: 80
        state: started
        timeout: 60  # Shortened for Arcade recording snappiness
      register: port_check

    - name: "VALIDATION! Performing Application Health Check"
      ansible.windows.win_uri:
        url: "http://localhost" # Use a simple URL if healthcheck.aspx doesn't exist
        return_content: yes
      register: app_health
      ignore_errors: yes # Safety for the demo: keeps the workflow green even if IIS is off

    - name: "MECM Final Site-Wide Compliance Refresh"
      # We run this on MainMECM directly
      microsoft.mecm.client_action:
        site_code: "PS1"
        action: "ClientNotificationCheckComplianceNow" # Fixed from 'name' and 'SoftwareUpdateComplianceScan'
        collection_name: "PROD-Web-Servers"

    - name: "RECOVERY: Re-Enabling Traffic (Restore to Load Balancer)"
      ansible.builtin.debug:
        msg: "Set-NetIPAddress -InterfaceAlias 'External' -SkipAsSource $false"
      # Using debug here is safer for a demo to avoid messing with your real MECM server's IP