---
- name: Define Compliance Policy
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Create a Software Update Group for Web Patching
      microsoft.mecm.software_update_group:
        site_code: "PS1"
        name: "{{ update_group }}"
        software_update_names: "{{ updates_list }}"
        state: present
      register: sug_info

    - name: Deploy the Policy as 'Required' to Web Servers
      microsoft.mecm.software_update_deployment:
        site_code: "PS1"
        name: "Security-Web-Patching"
        collection_name: "PROD-Web-Servers"
        software_update_group_name: "{{ update_group }}"
        deployment_type: required
        deployment_timezone: "UTC"
        available_time: "2026-01-19T14:00:00"
        deadline_time: "2026-01-20T14:00:00"
        description: "Demo Security deployment for compliance"
        state: present
