---
- name: Compliance Assertion
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Check Deployment Status from MECM
      # delegate_to: MainMECM
      microsoft.mecm.software_update_deployment_info:
        site_code: "PS1"
        name: "Monthly-Web-Patching"
      register: deploy_status

    - name: Assert all servers are compliant
      # This will fail if any server is 'Non-Compliant' or 'Missing'
      ansible.builtin.assert:
        that:
          - deploy_status.software_update_deployments | length > 0
          - deploy_status.software_update_deployments[0].compliant_count == deploy_status.software_update_deployments[0].target_count
        fail_msg: "Compliance Failure: Web servers are missing required patches. Triggering Drain Workflow."