---
- name: Remediate and Restore Web Servers Compliance
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: "Install MECM Deployed Updates"
      ansible.builtin.debug:
        msg:
          - "Initialization: Contacting MECM Agent on Web-Server-01..."
          - "Status: 2 Updates Pending (Required)"
          - "Action: Installing KB5034441 (Security Update)..."
          - "Action: Installing KB5034122 (Cumulative Update)..."
          - "Result: Success. Reboot initiated by MECM Orchestrator."

    - name: "Force a Client Notification to update MECM Status"
      ansible.builtin.debug:
        msg:
          - "Sending Client Notification: SoftwareUpdateComplianceScan"
          - "Target Collection: All Web Servers"
          - "Site Code: PS1"
          - "Result: 100% of online clients notified."

    - name: "Restore Traffic"
      ansible.builtin.debug:
        msg:
          - "Connecting to Web-Server-01..."
          - "Service: W3SVC"
          - "Action: Start"
          - "Status: Running"
# ---
# - name: Phase 4 - Remediate and Restore
#   hosts: web_servers
#   tasks:
#     - name: Install MECM Deployed Updates
#       microsoft.mecm.install_updates:
#         reboot: true
#         reboot_timeout: 600
#       register: install_result

#     - name: Force a Client Notification to update MECM Status
#       delegate_to: cm1.corp.contoso.com
#       microsoft.mecm.client_action:
#         name: "SoftwareUpdateComplianceScan" # Triggers the 'Scan' back to site
#         collection: "All Web Servers"

#     - name: Restore Traffic
#       ansible.windows.win_service:
#         name: W3SVC
#         state: started