---
- name: Service Restore & Compliance Sync
  hosts: PROD_Web_Servers
  gather_facts: false
  serial: 1
  tasks:
    - name: "Starting IIS Web Service (W3SVC)"
      ansible.windows.win_shell: |
        Write-Host "Action: Start-Service W3SVC"
        Write-Host "Status: Running"
      changed_when: true

    - name: "Waiting for Web Service Port (80) to be Ready"
      ansible.windows.win_wait_for:
        port: 80
        state: started
        timeout: 45

    - name: "MECM Final Site-Wide Compliance Refresh"
      delegate_to: MainMECM
      microsoft.mecm.client_action:
        site_code: "PS1"
        action: "ClientNotificationCheckComplianceNow"
        collection_name: "PROD-Web-Servers"
      run_once: true

    - name: "Re-Enabling Traffic (Restore to Load Balancer)"
      ansible.windows.win_shell: |
        Write-Host "MECM Compliance Verified. Restoring Traffic Flow..."
      changed_when: true
