---
- name: Drain Traffic from Web Servers
  hosts: PROD_Web_Servers
  gather_facts: false
  connection: local
  serial: 1
  tasks:
    - name: "LOAD BALANCER: Removing {{ inventory_hostname }} from Pool"
      ansible.builtin.debug:
        msg: "Executing: Set-LoadBalancerNode -State Offline -Node {{ inventory_hostname }}"
      changed_when: true # Forces the "Changed" status in AAP

    - name: "DRAIN: Waiting for active connections to drop"
      ansible.builtin.pause:
        seconds: 3

    - name: "SERVICE: Stopping IIS Web Services"
      ansible.builtin.debug:
        msg: "Executing: Stop-Service W3SVC on {{ inventory_hostname }}"
      changed_when: true # Forces the "Changed" status in AAP

    - name: "VERIFY: W3SVC service confirmed stopped"
      ansible.builtin.debug:
        msg: "Status: Service Stopped. Port 80 is no longer listening."
