---
- name: Compliance Assertion
  hosts: MainMECM
  gather_facts: false
  tasks:
    - name: Check Deployment Status from MECM
      microsoft.mecm.software_update_deployment_info:
        site_code: "PS1"
        collection_name: "PROD-Web-Servers"
      register: deploy_status

    - name: "Audit Deployment Configuration"
      ansible.builtin.debug:
        msg: 
          - "Checking Policy: Security-Web-Patching"
          - "Target Fleet: PROD-Web-Servers"
          - "Status: {{ 'Deployment Found' if deploy_status.software_update_deployments | length > 0 else 'Querying MECM Site Database...' }}"

    - name: Assert Deployment is Enforced
      ansible.builtin.assert:
        that:
          - deploy_status.software_update_deployments | length > 0
          - deploy_status.software_update_deployments[0].deadline_time | default('') != ""
        fail_msg: "Compliance Failure: Deployment 'Security-Web-Patching' is not yet enforced on the Web Fleet."