---
- name: Verify MECM and Windows Collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List installed collections
      ansible.builtin.command: ansible-galaxy collection list
      register: collection_output
      changed_when: false

    - name: Show collections
      ansible.builtin.debug:
        var: collection_output.stdout_lines
